apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-01cloud-data
  namespace: 01cloud-staging
spec:
  storageClassName: "openebs-kernel-nfs"
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
