apiVersion: v1
items:
- apiVersion: networking.k8s.io/v1
  kind: Ingress
  metadata:
    annotations:
      kubernetes.io/ingress.class: nginx
    name: 01cloud-admin
  spec:
    rules:
    - host: {{.Values.env.hostAdmin}}
      http:
        paths:
        - backend:
            service:
              name: cloud-admin
              port:
                number: 80
          path: /
          pathType: ImplementationSpecific
    tls:
    - hosts:
      - {{.Values.env.hostAdmin}}
      secretName: zerone-tls-cert
- apiVersion: networking.k8s.io/v1
  kind: Ingress
  metadata:
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.org/websocket-services: cloud-api
    name: 01cloud-api
  spec:
    rules:
    - host: {{.Values.env.hostApi}}
      http:
        paths:
        - backend:
            service:
              name: cloud-api
              port:
                number: 8081
          path: /
          pathType: ImplementationSpecific
    tls:
    - hosts:
      - {{.Values.env.hostApi}}
      secretName: zerone-tls-cert
- apiVersion: networking.k8s.io/v1
  kind: Ingress
  metadata:
    annotations:
      kubernetes.io/ingress.class: nginx
    name: 01cloud-ui
  spec:
    rules:
    - host: {{.Values.env.hostUI}}
      http:
        paths:
        - backend:
            service:
              name: cloud-ui
              port:
                number: 80
          path: /
          pathType: ImplementationSpecific
    tls:
    - hosts:
      - {{.Values.env.hostUI}}
      secretName: zerone-tls-cert
- apiVersion: networking.k8s.io/v1
  kind: Ingress
  metadata:
    annotations:
      ingressClassName: nginx
    name: 01cloud-terminal
  spec:
    rules:
    - host: {{.Values.env.hostTerminal}}
      http:
        paths:
        - backend:
            service:
              name: cloud-terminal
              port:
                number: 8080
          path: /
          pathType: ImplementationSpecific
    tls:
    - hosts:
      - {{.Values.env.hostTerminal}}
      secretName: zerone-tls-cert
kind: List
metadata:
  resourceVersion: ""
