apiVersion: v1
items:
- apiVersion: v1
  data:
    API_SECRET: {{ .Values.secret.API_SECRET }}
    DB_PASSWORD: {{ .Values.secret.DB_PASSWORD }}
    DB_URL: {{ .Values.secret.DB_URL }}
    MONGO_URL: {{ .Values.secret.MONGO_URL }}
    RABBITMQ_URL: {{ .Values.secret.RABBITMQ_URL }}
    RABBITMQ_PASSWORD: {{ .Values.secret.RABBITMQ_PASSWORD }}
    SMTP_PASSWORD: {{ .Values.secret.SMTP_PASSWORD }}
    MODE: {{ .Values.secret.MODE }}
  kind: Secret
  metadata:
    name: env-secrets
  type: Opaque
- apiVersion: v1
  data:
    tls.crt: {{ .Values.secret.TLS_CRT }}
    tls.key: {{ .Values.secret.TLS_KEY }}
  kind: Secret
  metadata:
    annotations:
      cert-manager.io/alt-names: '*.staging.01cloud.dev,staging.01cloud.dev'
      cert-manager.io/certificate-name: zerone-cloud-staging-crt
      cert-manager.io/common-name: staging.01cloud.dev
      cert-manager.io/ip-sans: ""
      cert-manager.io/issuer-group: ""
      cert-manager.io/issuer-kind: ClusterIssuer
      cert-manager.io/issuer-name: letsencrypt-issuer
      cert-manager.io/uri-sans: ""
    name: zerone-tls-cert
  type: kubernetes.io/tls

  # metadata:
  #   annotations:
  #     cert-manager.io/alt-names: '*.staging.01cloud.dev,staging.01cloud.dev'
  #     cert-manager.io/certificate-name: zerone-cloud-staging-crt
  #     cert-manager.io/common-name: staging.01cloud.dev
  #     cert-manager.io/ip-sans: ""
  #     cert-manager.io/issuer-group: ""
  #     cert-manager.io/issuer-kind: ClusterIssuer
  #     cert-manager.io/issuer-name: letsencrypt-issuer
  #     cert-manager.io/uri-sans: ""
  #   name: zerone-tls-cert
  # type: kubernetes.io/tls
kind: List
metadata:
  resourceVersion: ""
