apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  name: staging-sa
secrets:
- name: staging-sa
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: staging-sa
rules:
- apiGroups:
  - "*"
  resources:
  - "*"
  verbs:
  - "*"
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: staging-sa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: staging-sa
subjects:
- kind: ServiceAccount
  name: staging-sa
  namespace: {{ .Release.Namespace }}
---

apiVersion: v1
data:
  ca.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM1ekNDQWMrZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJeU1EZ3pNVEE1TkRBMU0xb1hEVE15TURneU9EQTVOREExTTFvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBT0xlCm9xY0dQVnRaSTlyK0hXd2RhYTVDWUFFVHJYQWlkWm1ka2pYVGVBbDVVanJqc2xFVUI5K21zWkFRbjZ1N3RnMXEKSkxUMEtmbzRaWlJ4U2RyYmRZMEs0eDVXL0tYMGFKVEpDSXdJVzFDcWJOZi8rejhyY0lyNTBhQkFjTWV0UWZRKwp4T3NrRWEzTDh2R2UvTmc2V0hsL2x2WVFKOHJkaUdUK2krY2h3YXZheGZMSHBmTGRIZUYvK0pKNURsbmdwT3pLCjZ5cnZjTGl2QUZtVWxhU01qRWdWekQ2YldiNEc2SWNIY3VCa29MQlVtZVNJL1BmT2tvQVZ5ZEhJU2FNSG1BekEKR283REI1eUR0K0h0MWJHTmlkUmVnVDFkeExxdkhpWUhPWDJoNVp2WEV1NHgrMEZxS0xaYTNuTGh4Mkg1RDhkbgo2bEJ5aTRWTFE5VXlhZE4vczA4Q0F3RUFBYU5DTUVBd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZCdDkwdnZ2c0pSTzg3Z2tYeXJyakwrRkEwdUhNQTBHQ1NxR1NJYjMKRFFFQkN3VUFBNElCQVFDcUcxdzVBN01zVVpESnBlNE9MMTN1a0N2a2VKdHBhQWxzU3Raa2hxc2h3RzZFVmJCQwpkeWhpNWtHQkdKWmsyTXBvYThYRGlzYVFacDd1NW1yQUk3WFdFZitjcmFlUENIbzV0Q21xMDNxOTY4dEFSdFhJCi94L3JFTXVoNm5GM3JYdGg0YThxYTVPc2p4M2M4WlMrLzkwTTZ3TXZML1RQbmtxZEVsZE1SYjFNQ0JHQ2l4dHYKRkNKRmpJNkJVZlFUNlU5c2V0MGtVbVdTRmlRNHdVNUJJemUwQ1pCRDlUWU42bExRelNUZnFPNlJxZ3VZZ3ExdwpFMFhseUh3aFRiY3JRdkw5MERlSHBFTTRrSTJicC9VN3NkcTJrUzJqNi9OTm1qTzNkVGppRmhoZ29zWU1qRFN0CmJuSkthL291Rkc3NjZrcG9BNktCcENFU1lhWHY1R0lVend4WgotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  token: ZXlKaGJHY2lPaUpTVXpJMU5pSXNJbXRwWkNJNklrUmhNVmxpTWpsd2QwRjVWMnRPTUdWd2MwZzNZbDlDVTNGbFdHNUpNV1UzZDFWM1NuWndVM2hPVDJjaWZRLmV5SnBjM01pT2lKcmRXSmxjbTVsZEdWekwzTmxjblpwWTJWaFkyTnZkVzUwSWl3aWEzVmlaWEp1WlhSbGN5NXBieTl6WlhKMmFXTmxZV05qYjNWdWRDOXVZVzFsYzNCaFkyVWlPaUowWlhOMElpd2lhM1ZpWlhKdVpYUmxjeTVwYnk5elpYSjJhV05sWVdOamIzVnVkQzl6WldOeVpYUXVibUZ0WlNJNkluSmhZbUpwZEcxeExYUnZhMlZ1TFdObWJqWjNJaXdpYTNWaVpYSnVaWFJsY3k1cGJ5OXpaWEoyYVdObFlXTmpiM1Z1ZEM5elpYSjJhV05sTFdGalkyOTFiblF1Ym1GdFpTSTZJbkpoWW1KcGRHMXhJaXdpYTNWaVpYSnVaWFJsY3k1cGJ5OXpaWEoyYVdObFlXTmpiM1Z1ZEM5elpYSjJhV05sTFdGalkyOTFiblF1ZFdsa0lqb2lNVE0xTTJJM01ETXROemt6TkMwME5XWTBMVGs1T0RndE5ERXdOR1ZrTXpZNFlXVTFJaXdpYzNWaUlqb2ljM2x6ZEdWdE9uTmxjblpwWTJWaFkyTnZkVzUwT25SbGMzUTZjbUZpWW1sMGJYRWlmUS5XX016LVg3Ukdoa1otdGF0eW9JNGNXY2JwLXVxTXNVdnI0aFhJZDdRODFaajJhTmlGUVBjaWU3MkZnc0lHYU54R2VObXlON0RoYkZUeXA2MHA4UVpEdHRDWVlmaU5CT0M1WjZfaVZBRER1aDZRSVFqd2VOTlJCQmxCVkhsUW5mbG14YjVOZ0ZxR1RvN3VoNEd2LXMzd2l1Y3NoSjl1QjRfZWpmS2VoSmxkQTFTQWNIVmVvdHlNbUNoUFBxcHBrT0l5RzdJWnlpZllrZ3VsME9MNXJZLTBMajRkclBhRzFYNHdEeldQS0lHU1FoYU85dlphOC1xV2J6YXlNZ05zc2FhaHNOd0NHZWgwZ29aVm8tdmJCR3I5dUk5TnZtRmJRZ2V2ZHZ0aExucHZVQUVSeFFBZDRiY2JINXdqQ244TWRZQkJxQTBpdHluaVZuUXhUN05ZT21rbFE=
kind: Secret
metadata:
  annotations:
    kubernetes.io/service-account.name: staging-sa
  name: staging-sa
type: kubernetes.io/service-account-token
