apiVersion: v1
data:
  config.toml: <base 64 config converted from the step 6 of README.md>
kind: Secret
metadata:
  annotations:
    meta.helm.sh/release-name: gchat
    meta.helm.sh/release-namespace: monitoring
  creationTimestamp: "2023-03-30T08:37:01Z"
  labels:
    app.kubernetes.io/instance: gchat
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: alertmanager-gchat-integration
    app.kubernetes.io/version: 1.0.5
    helm.sh/chart: alertmanager-gchat-integration-1.0.5
  name: gchat-alertmanager-gchat-integration
  namespace: monitoring
  resourceVersion: "1236455575"
  uid: 019a6e6f-5592-4472-ac81-e7637f1ebaff
type: Opaque
